# Generated by Django 3.2.25 on 2025-06-09 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_auto_20250609_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='type',
            name='category',
        ),
        migrations.AddField(
            model_name='sweet',
            name='categories',
            field=models.ManyToManyField(related_name='sweets', to='sweets.Category'),
        ),
        migrations.AddField(
            model_name='type',
            name='categories',
            field=models.ManyToManyField(related_name='types', to='sweets.Category'),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sweets.type'),
        ),
    ]
