# Generated by Django 3.2.25 on 2025-06-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0003_auto_20250609_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
