# Generated by Django 3.2.25 on 2025-06-15 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sweets', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweetreview',
            name='comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sweetreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sweetreview',
            unique_together={('sweet', 'user')},
        ),
    ]
